[template]
src = "duply_conf.tmpl"
dest = "/etc/duply/prod-backup/conf"
mode = "0700"
keys = [
    "/duply/gpg/key",
    "/duply/gpg/pw",
    "/duply/target/url",
    "/duply/target/user",
    "/duply/target/pass",
    "/duply/source",
    "/duply/maxage",
    "/duply/maxfullbkpage"
]
